### PR TITLE
Export file path validity check enhancement and test driver implementation

### PR DESCRIPTION
**Pull request by low5545**

### CODE REVIEW

**Comment by low5545** [comment]
Suspect that the temporary file path provided in AppVeyor contains prohibited characters, investigation in progress.

**Comment by low5545** [comment]
This PR is ready for review

**Review by yunpengn — APPROVED** [review]
more `Exception` classes are defined. Looks good to me

**Comment by junyango** [comment]
improvement in coverage for inclusion of tests. looks good.

**Pull request merged**
